import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect } from 'react';
import { useProviderStore } from '../../store/providerStore';
import { useProviderStatus } from '../../hooks/useProviderStatus';
function ProviderCard({ title, description, enabled, onToggle, onSave, onTest, isSaving, testResult, children, }) {
    return (_jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 dark:text-white", children: title }), _jsx("p", { className: "text-sm text-gray-600 dark:text-gray-400", children: description })] }), _jsxs("label", { className: "relative inline-flex items-center cursor-pointer", children: [_jsx("input", { type: "checkbox", checked: enabled, onChange: (e) => onToggle(e.target.checked), className: "sr-only peer" }), _jsx("div", { className: "w-11 h-6 bg-gray-200 peer-focus:outline-none rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600" })] })] }), enabled && (_jsxs("div", { className: "space-y-4", children: [children, _jsxs("div", { className: "flex items-center justify-between pt-4 border-t border-gray-200 dark:border-gray-700", children: [_jsx("div", { className: "flex items-center gap-3", children: testResult && (_jsx("span", { className: `text-sm ${testResult.status === 'ok'
                                        ? 'text-green-600 dark:text-green-400'
                                        : testResult.status === 'error'
                                            ? 'text-red-600 dark:text-red-400'
                                            : 'text-gray-600 dark:text-gray-400'}`, children: testResult.status === 'testing'
                                        ? 'Testing...'
                                        : testResult.status === 'ok'
                                            ? '✓ Connected'
                                            : testResult.message || 'Connection failed' })) }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { onClick: onTest, disabled: isSaving, className: "px-3 py-1.5 text-sm bg-gray-100 text-gray-700 rounded-md hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600 disabled:opacity-50", children: "Test Connection" }), _jsx("button", { onClick: onSave, disabled: isSaving, className: "px-3 py-1.5 text-sm bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50", children: isSaving ? 'Saving...' : 'Save' })] })] })] }))] }));
}
function TextInput({ label, value, onChange, placeholder, required }) {
    return (_jsxs("div", { children: [_jsxs("label", { className: "block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1", children: [label, required && _jsx("span", { className: "text-red-500 ml-1", children: "*" })] }), _jsx("input", { type: "text", value: value, onChange: (e) => onChange(e.target.value), placeholder: placeholder, className: "w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white" })] }));
}
export function Providers() {
    const { s3, gcs, nas, testResults, isSaving, load, setS3, setGcs, setNas, saveS3, saveGcs, saveNas, testProvider, } = useProviderStore();
    // Subscribe to provider status events
    useProviderStatus();
    useEffect(() => {
        load();
    }, [load]);
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900 dark:text-white", children: "Backup Providers" }), _jsx("p", { className: "text-gray-600 dark:text-gray-400 mt-1", children: "Configure where your files are backed up" })] }), _jsxs("div", { className: "space-y-6", children: [_jsxs(ProviderCard, { title: "Amazon S3", description: "Back up to Amazon S3 storage", enabled: s3.enabled, onToggle: (enabled) => setS3({ ...s3, enabled }), onSave: saveS3, onTest: () => testProvider('s3'), isSaving: isSaving.s3, testResult: testResults.s3, children: [_jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsx(TextInput, { label: "Bucket", value: s3.bucket, onChange: (bucket) => setS3({ ...s3, bucket }), placeholder: "my-backup-bucket", required: true }), _jsx(TextInput, { label: "Region", value: s3.region, onChange: (region) => setS3({ ...s3, region }), placeholder: "us-east-1", required: true })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsx(TextInput, { label: "Profile", value: s3.profile, onChange: (profile) => setS3({ ...s3, profile }), placeholder: "shadow" }), _jsx(TextInput, { label: "Prefix", value: s3.prefix, onChange: (prefix) => setS3({ ...s3, prefix }), placeholder: "backups/" })] })] }), _jsxs(ProviderCard, { title: "Google Cloud Storage", description: "Back up to Google Cloud Storage", enabled: gcs.enabled, onToggle: (enabled) => setGcs({ ...gcs, enabled }), onSave: saveGcs, onTest: () => testProvider('gcs'), isSaving: isSaving.gcs, testResult: testResults.gcs, children: [_jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsx(TextInput, { label: "Bucket", value: gcs.bucket, onChange: (bucket) => setGcs({ ...gcs, bucket }), placeholder: "my-backup-bucket", required: true }), _jsx(TextInput, { label: "Project ID", value: gcs.project_id, onChange: (project_id) => setGcs({ ...gcs, project_id }), placeholder: "my-project-12345", required: true })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsx(TextInput, { label: "Credentials Path", value: gcs.credentials_path, onChange: (credentials_path) => setGcs({ ...gcs, credentials_path }), placeholder: "/path/to/service-account.json", required: true }), _jsx(TextInput, { label: "Prefix", value: gcs.prefix, onChange: (prefix) => setGcs({ ...gcs, prefix }), placeholder: "backups/" })] })] }), _jsx(ProviderCard, { title: "Network Attached Storage (NAS)", description: "Back up to a local NAS or mounted drive", enabled: nas.enabled, onToggle: (enabled) => setNas({ ...nas, enabled }), onSave: saveNas, onTest: () => testProvider('nas'), isSaving: isSaving.nas, testResult: testResults.nas, children: _jsx(TextInput, { label: "Mount Path", value: nas.mount_path, onChange: (mount_path) => setNas({ ...nas, mount_path }), placeholder: "/Volumes/BackupDrive", required: true }) })] })] }));
}
